name: fluent-amqp
version: git
summary: AMQP utilities
icon: docs/logo.svg
description: |
  fluent-amqp contains set of CLI tools to operate with AMQP broker.
  Provides fluent and easy wrapper over [streadway-amqp](https://github.com/streadway/amqp) API.
  Adds such features like:
  - Reconnectiong. Will restore all defined infrastructure
  - Non-blocking processing of messages
  - Optional auto-requeue (with delay)
  - Signing and verifiying messages by public/private pair

license: MIT
grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.11.2
  cli:
    after: [go]
    plugin: go
    go-importpath: github.com/reddec/fluent-amqp

apps:
  amqp-exec:
    command: bin/amqp-exec
    plugs:
      - network
  amqp-send:
    command: bin/amqp-send
    plugs:
      - network
  amqp-recv:
    command: bin/amqp-recv
    plugs:
      - network